version: "3"

vars:
  PROJECT_HOME:
    sh: pwd
  KUBECONFIG: "{{.PROJECT_HOME}}/.kube/config"
  K3D_CLUSTER_NAME: polaris-local-forge
  K3S_VERSION: v1.31.5-k3s1
  FEATURES_DIR: "{{.PROJECT_HOME}}/k8s"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"

tasks:
  # ============================================
  # Installation Tasks
  # ============================================

  install:uv:
    desc: Install uv Python package manager
    cmds:
      - |
        if ! command -v uv &> /dev/null; then
          echo "Installing uv..."
          pip install uv || curl -LsSf https://astral.sh/uv/install.sh | sh
        else
          echo "uv is already installed ($(uv --version))"
        fi
    status:
      - command -v uv

  # ============================================
  # Setup and Initialization Tasks
  # ============================================

  setup:python:
    desc: Set up Python environment using uv
    deps:
      - install:uv
    cmds:
      - uv python pin 3.12
      - uv venv
      - uv sync
      - |
        echo ""
        echo "✅ Python environment setup complete!"
        echo ""
        echo "📌 Next step: Activate the virtual environment in your shell:"
        echo "   source .venv/bin/activate"
        echo ""

  prepare:
    desc: Generate required sensitive files from templates using Ansible
    preconditions:
      - sh: test -f .venv/bin/activate || test -f .venv/Scripts/activate
        msg: "Python venv not found. Run 'task setup:python' first."
    cmds:
      - uv run polaris-forge prepare {{if .TAGS}}--tags={{.TAGS}}{{end}}

  # ============================================
  # Cluster Management Tasks
  # ============================================

  cluster:create:
    desc: Create the k3d cluster and deploy initial components
    deps:
      - prepare
    cmds:
      - uv run polaris-forge cluster create

  cluster:bootstrap-check:
    desc: Wait for bootstrap deployments to be ready
    cmds:
      - uv run polaris-forge cluster bootstrap-check

  cluster:polaris-check:
    desc: Wait for polaris deployments to be ready
    cmds:
      - uv run polaris-forge cluster polaris-check

  cluster:delete:
    desc: Delete the k3d cluster
    cmds:
      - uv run polaris-forge cluster delete

  cluster:reset:
    desc: Delete and recreate cluster with fresh catalog
    cmds:
      - task: cluster:delete
      - task: cluster:create
      - task: cluster:bootstrap-check
      - task: polaris:deploy
      - task: cluster:polaris-check
      - task: catalog:setup
      - 'echo ""'
      - 'echo "✅ Cluster reset complete!"'
      - 'echo "All services are running with a fresh catalog"'

  # ============================================
  # Polaris Deployment Tasks
  # ============================================

  polaris:deploy:
    desc: Deploy Polaris to the cluster
    cmds:
      - uv run polaris-forge polaris deploy

  polaris:check:
    desc: Ensure all Polaris deployments and jobs have succeeded
    cmds:
      - uv run polaris-forge polaris check

  polaris:purge:
    desc: Purge Polaris data
    cmds:
      - uv run polaris-forge polaris purge

  polaris:bootstrap:
    desc: Bootstrap Polaris (run after purge)
    cmds:
      - uv run polaris-forge polaris bootstrap

  polaris:reset:
    desc: Purge and re-bootstrap Polaris
    cmds:
      - uv run polaris-forge polaris reset

  # ============================================
  # Catalog Management Tasks
  # ============================================

  catalog:setup:
    desc: Set up demo catalog with s3 bucket, catalog, principal, and roles
    cmds:
      - uv run polaris-forge catalog setup {{if .TAGS}}--tags={{.TAGS}}{{end}}

  catalog:generate-notebook:
    desc: Generate and prepare verification notebook
    cmds:
      - uv run polaris-forge catalog generate-notebook

  catalog:verify:duckdb:
    desc: Verify Polaris catalog using DuckDB Iceberg extension (Python)
    cmds:
      - uv run polaris-forge catalog verify {{.CLI_ARGS}}
    preconditions:
      - sh: test -f {{.PROJECT_HOME}}/work/principal.txt
        msg: "Principal credentials not found. Run 'task catalog:setup' first."

  catalog:verify:sql:
    desc: Verify Polaris catalog using DuckDB CLI with SQL script
    cmds:
      - uv run polaris-forge catalog verify-sql
    preconditions:
      - sh: test -f {{.PROJECT_HOME}}/scripts/explore_catalog.sql
        msg: "SQL script not found. Run 'task catalog:setup' first to generate it."
      - sh: command -v duckdb
        msg: "DuckDB CLI not found. Install from https://duckdb.org/docs/installation/"

  catalog:explore:sql:
    desc: Explore Polaris catalog with DuckDB CLI in interactive mode
    cmds:
      - uv run polaris-forge catalog explore-sql
    preconditions:
      - sh: test -f {{.PROJECT_HOME}}/scripts/explore_catalog.sql
        msg: "SQL script not found. Run 'task catalog:setup' first to generate it."
      - sh: command -v duckdb
        msg: "DuckDB CLI not found. Install from https://duckdb.org/docs/installation/"

  verify:
    desc: Verify Polaris catalog setup (alias for catalog:verify:duckdb)
    cmds:
      - task: catalog:verify:duckdb
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  verify:sql:
    desc: Verify Polaris catalog setup using SQL (alias for catalog:verify:sql)
    cmds:
      - task: catalog:verify:sql
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  catalog:info:
    desc: Get catalog configuration details from Polaris API
    cmds:
      - |
        echo "Fetching catalog configuration..."
        REALM=$(head -1 {{.PROJECT_HOME}}/work/principal.txt | cut -d',' -f1)
        CLIENT_ID=$(head -1 {{.PROJECT_HOME}}/work/principal.txt | cut -d',' -f2)
        CLIENT_SECRET=$(head -1 {{.PROJECT_HOME}}/work/principal.txt | cut -d',' -f3)

        # Get access token
        TOKEN=$(curl -s -X POST "http://localhost:18181/api/catalog/v1/oauth/tokens" \
          -H "Authorization: Bearer ${CLIENT_ID}:${CLIENT_SECRET}" \
          -H "Polaris-Realm: ${REALM}" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=client_credentials&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&scope=PRINCIPAL_ROLE:ALL" \
          | jq -r '.access_token')

        if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
          echo "❌ Failed to get access token"
          exit 1
        fi

        echo ""
        echo "=== Catalog Configuration for 'polardb' ==="
        echo ""

        # Get catalog configuration
        curl -s "http://localhost:18181/api/management/v1/catalogs/polardb" \
          -H "Authorization: Bearer ${TOKEN}" \
          -H "Polaris-Realm: ${REALM}" \
          | jq '.'

        echo ""
        echo "=== Key S3 Configuration ==="
        echo ""
        curl -s "http://localhost:18181/api/management/v1/catalogs/polardb" \
          -H "Authorization: Bearer ${TOKEN}" \
          -H "Polaris-Realm: ${REALM}" \
          | jq '{
              properties: .properties,
              storageConfigInfo: .storageConfigInfo
            }'
    preconditions:
      - sh: test -f {{.PROJECT_HOME}}/work/principal.txt
        msg: "Credentials file not found. Run 'task catalog:setup' first."
      - sh: command -v jq
        msg: "jq is required for this task. Install with: brew install jq"

  catalog:cleanup:
    desc: Cleanup Polaris catalog resources
    cmds:
      - uv run polaris-forge catalog cleanup {{if .TAGS}}--tags={{.TAGS}}{{end}}

  catalog:reset:
    desc: Cleanup and recreate catalog (keeps cluster running)
    cmds:
      - task: catalog:cleanup
      - task: catalog:setup
      - 'echo ""'
      - 'echo "✅ Catalog reset complete!"'
      - 'echo ""'
      - 'echo "📝 Verification options:"'
      - 'echo "  - Run DuckDB verification: task verify"'
      - 'echo "  - Generate notebook: task catalog:generate-notebook"'

  catalog:reset:full:
    desc: Full reset - purge Polaris database and recreate catalog
    cmds:
      - echo "⚠️  This will purge the entire Polaris database and recreate from scratch"
      - task: polaris:reset
      - task: catalog:setup
      - 'echo ""'
      - 'echo "✅ Full catalog reset complete!"'
      - 'echo "Polaris database was purged and catalog recreated"'
      - 'echo ""'
      - 'echo "📝 Verification options:"'
      - 'echo "  - Run DuckDB verification: task verify"'
      - 'echo "  - Generate notebook: task catalog:generate-notebook"'

  # ============================================
  # Logging and Troubleshooting Tasks
  # ============================================

  logs:polaris:
    desc: Stream Polaris server logs
    cmds:
      - kubectl logs -f -n polaris deployment/polaris

  logs:bootstrap:
    desc: View Polaris bootstrap job logs
    cmds:
      - kubectl logs -f -n polaris jobs/polaris-bootstrap

  logs:purge:
    desc: View Polaris purge job logs
    cmds:
      - kubectl logs -f -n polaris jobs/polaris-purge

  logs:postgresql:
    desc: Stream PostgreSQL logs
    cmds:
      - kubectl logs -f -n polaris statefulset/postgresql

  logs:rustfs:
    desc: Stream RustFS logs
    cmds:
      - kubectl logs -f -n rustfs deployment/rustfs

  # ============================================
  # Troubleshooting Tasks
  # ============================================

  troubleshoot:events:
    desc: Show recent events in polaris namespace
    cmds:
      - kubectl get events -n polaris --sort-by='.lastTimestamp'

  troubleshoot:polaris:
    desc: Troubleshoot Polaris deployment issues
    cmds:
      - kubectl get events -n polaris --sort-by='.lastTimestamp'
      - kubectl describe pod -n polaris -l app=polaris

  troubleshoot:rustfs:
    desc: Troubleshoot RustFS connectivity
    cmds:
      - kubectl get svc -n rustfs
      - kubectl exec -it -n rustfs deployment/rustfs -- mc ls local

  troubleshoot:postgresql:
    desc: Troubleshoot PostgreSQL connectivity
    cmds:
      - kubectl get svc -n polaris postgresql-hl
      - kubectl exec -it -n polaris postgresql-0 -- pg_isready -h localhost

  # ============================================
  # Convenience Compound Tasks
  # ============================================

  setup:all:
    desc: Complete setup - prepare files, create cluster, deploy Polaris, setup catalog
    cmds:
      - task: cluster:create
      - task: cluster:bootstrap-check
      - task: polaris:deploy
      - task: cluster:polaris-check
      - task: catalog:setup
      - task: verify
      - 'echo ""'
      - 'echo "✅ Setup complete 🎉"'
      - 'echo ""'
      - 'echo "📝 Additional verification options:"'
      - 'echo "  - Run DuckDB verification again: task verify"'
      - 'echo "  - Generate PyIceberg notebook: task catalog:generate-notebook"'
      - 'echo "  - Open notebook at: {{.PROJECT_HOME}}/notebooks/verify_setup.ipynb"'

  reset:all:
    desc: Complete reset - delete cluster, recreate everything with fresh catalog
    cmds:
      - task: cluster:reset

  clean:all:
    desc: Delete cluster and all resources
    cmds:
      - task: cluster:delete

  # ============================================
  # Quick Reference Tasks
  # ============================================

  status:
    desc: Show status of all deployments
    cmds:
      - echo "=== Polaris Namespace ==="
      - kubectl get all -n polaris
      - echo ""
      - echo "=== RustFS Namespace ==="
      - kubectl get all -n rustfs

  urls:
    desc: Display service URLs and credentials locations
    cmds:
      - 'echo "Service URLs:"'
      - 'echo "  Polaris UI:  http://localhost:18181"'
      - 'echo "  Credentials: {{.PROJECT_HOME}}/k8s/polaris/.bootstrap-credentials.env"'
      - 'echo ""'
      - 'echo "  Adminer:     http://localhost:18080"'
      - 'echo "  PostgreSQL:  postgresql.polaris (check {{.FEATURES_DIR}}/postgresql.yaml)"'
      - 'echo ""'
      - 'echo "  RustFS S3:   http://localhost:9000"'
      - 'echo "  RustFS UI:   http://localhost:9001"'
      - 'echo "  Credentials: admin/password"'

  help:
    desc: Show available tasks with descriptions
    cmds:
      - task --list
