# Copyright 2025 Snowflake Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3"

vars:
  PROJECT_HOME:
    sh: pwd
  KUBECONFIG: "{{.PROJECT_HOME}}/.kube/config"
  K3D_CLUSTER_NAME: polaris-local-forge
  K3S_VERSION: v1.35.1-k3s1
  FEATURES_DIR: "{{.PROJECT_HOME}}/k8s"
  PODMAN_MACHINE: k3d

silent: true

env:
  KUBECONFIG: "{{.KUBECONFIG}}"

includes:
  podman: ./taskfiles/podman.yml
  cluster: ./taskfiles/cluster.yml
  polaris: ./taskfiles/polaris.yml
  catalog: ./taskfiles/catalog.yml
  ops: ./taskfiles/ops.yml

tasks:
  # ============================================
  # Installation
  # ============================================

  install:uv:
    desc: Install uv Python package manager
    cmds:
      - |
        if ! command -v uv &> /dev/null; then
          echo "Installing uv..."
          pip install uv || curl -LsSf https://astral.sh/uv/install.sh | sh
        else
          echo "uv is already installed ($(uv --version))"
        fi
    status:
      - command -v uv

  # ============================================
  # Setup and Initialization
  # ============================================

  setup:python:
    desc: Set up Python environment using uv
    deps:
      - install:uv
    cmds:
      - uv python pin 3.12
      - uv venv
      - uv sync
      - |
        echo ""
        echo "Python environment setup complete."
        echo ""
        echo "Next step: Activate the virtual environment in your shell:"
        echo "  source .venv/bin/activate"
        echo ""

  prepare:
    desc: Generate required sensitive files from templates using Ansible
    preconditions:
      - sh: test -f .venv/bin/activate || test -f .venv/Scripts/activate
        msg: "Python venv not found. Run 'task setup:python' first."
    cmds:
      - uv run polaris-local-forge prepare {{if .TAGS}}--tags={{.TAGS}}{{end}}

  runtime:setup:
    desc: Ensure container runtime is ready (Podman machine setup if needed)
    cmds:
      - |
        RUNTIME=$(uv run polaris-local-forge config --output json 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('PLF_CONTAINER_RUNTIME',''))" 2>/dev/null || echo "")
        if [ "$RUNTIME" = "podman" ] && command -v podman > /dev/null 2>&1; then
          echo "Container runtime: podman"
          task podman:setup
        else
          echo "Container runtime: docker"
        fi

  runtime:teardown:
    desc: Stop container runtime after teardown (Podman machine stop if needed)
    cmds:
      - |
        RUNTIME=$(uv run polaris-local-forge config --output json 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('PLF_CONTAINER_RUNTIME',''))" 2>/dev/null || echo "")
        if [ "$RUNTIME" = "podman" ] && [ "$(uname)" = "Darwin" ] && command -v podman > /dev/null 2>&1; then
          task podman:stop
        fi

  setup:all:
    desc: Complete setup - runtime check, prepare files, create cluster, deploy Polaris, setup catalog, verify
    cmds:
      - task: runtime:setup
      - uv run polaris-local-forge setup --yes
      - task: catalog:verify:sql

  teardown:
    desc: Complete teardown - cleanup catalog, delete cluster, stop Podman machine
    cmds:
      - uv run polaris-local-forge teardown --yes
      - task: runtime:teardown

  reset:all:
    desc: Complete reset - delete cluster, recreate everything with fresh catalog
    cmds:
      - task: teardown
      - task: setup:all

  clean:all:
    desc: Delete cluster and all resources
    cmds:
      - uv run polaris-local-forge cluster delete --yes

  cluster:reset:
    desc: Delete and recreate cluster with fresh catalog
    cmds:
      - task: cluster:delete
      - task: cluster:create
      - task: cluster:bootstrap-check
      - task: polaris:deploy
      - task: cluster:polaris-check
      - task: catalog:setup
      - 'echo ""'
      - 'echo "Cluster reset complete."'
      - 'echo "All services are running with a fresh catalog."'

  catalog:reset:full:
    desc: Full reset - purge Polaris database and recreate catalog
    cmds:
      - echo "WARNING -- This will purge the entire Polaris database and recreate from scratch."
      - task: polaris:reset
      - task: catalog:setup
      - 'echo ""'
      - 'echo "Full catalog reset complete."'
      - 'echo "Polaris database was purged and catalog recreated."'
      - 'echo ""'
      - 'echo "Verification options:"'
      - 'echo "  - Run DuckDB verification: task verify"'
      - 'echo "  - Generate notebook: task catalog:generate-notebook"'

  # ============================================
  # Quick Reference / Aliases
  # ============================================

  doctor:
    desc: Check system prerequisites and health
    cmds:
      - uv run polaris-local-forge doctor

  doctor:json:
    desc: Check system prerequisites (JSON output for automation)
    cmds:
      - uv run polaris-local-forge doctor --output json

  config:
    desc: Show current configuration from .env file
    cmds:
      - uv run polaris-local-forge config

  status:
    desc: Show status of cluster and Polaris
    cmds:
      - uv run polaris-local-forge cluster status
      - echo ""
      - uv run polaris-local-forge polaris status

  verify:
    desc: Verify Polaris catalog setup (alias for catalog:verify:duckdb)
    cmds:
      - task: catalog:verify:duckdb
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  verify:sql:
    desc: Verify Polaris catalog setup using SQL (alias for catalog:verify:sql)
    cmds:
      - task: catalog:verify:sql
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

  # Version bumps (aliases for discoverability)
  bump:polaris:
    desc: Update Polaris to latest version from Docker Hub
    cmds:
      - task: polaris:bump-version

  bump:polaris:dry-run:
    desc: Show what Polaris version update would do
    cmds:
      - task: polaris:bump-version:dry-run

  bump:k3s:
    desc: Update K3S to latest version from Docker Hub
    cmds:
      - task: cluster:bump-k3s

  bump:k3s:dry-run:
    desc: Show what K3S version update would do
    cmds:
      - task: cluster:bump-k3s:dry-run

  help:
    desc: Show available tasks with descriptions
    cmds:
      - task --list
