# Copyright 2025 Snowflake Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Prepare the environment for setting up polaris
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - defaults/main.yml

  vars:
    plf_key_files:
      - "{{ plf_polaris_dir }}/rsa_key"
      - "{{ plf_polaris_dir }}/rsa_key.pub"
    plf_config_files:
      - file: "{{ plf_polaris_dir }}/.bootstrap-credentials.env"
        template: "templates/bootstrap-credentials.env.j2"
      - file: "{{ plf_features_dir }}/postgresql.yaml"
        template: "templates/postgresql.yml.j2"
      - file: "{{ plf_features_dir }}/polaris.yaml"
        template: "templates/polaris.yaml.j2"
      - file: "{{ plf_polaris_dir }}/polaris-secrets.yaml"
        template: "templates/polaris-secrets.yaml.j2"
      - file: "{{ plf_polaris_dir }}/.polaris.env"
        template: "templates/polaris.env.j2"
      - file: "{{ plf_output_base }}/.aws/config"
        template: "templates/aws-config.j2"
      - file: "{{ plf_output_base }}/.aws/credentials"
        template: "templates/aws-credentials.j2"
  pre_tasks:
    - name: Install required collections
      ansible.builtin.command: ansible-galaxy collection install community.crypto
      changed_when: false

  tasks:
    - name: Ensure required directories exists with secure permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0700"
      loop:
        - "{{ plf_work_dir }}"
        - "{{ plf_polaris_dir }}"
        - "{{ plf_output_base }}/.aws"
      tags:
        - rsa
        - setup

    - name: Check if RSA keys already exist
      ansible.builtin.stat:
        path: "{{ plf_polaris_dir }}/rsa_key"
      register: private_key_stat
      tags:
        - rsa
        - setup

    - name: Generate RSA key pair
      when: not private_key_stat.stat.exists
      block:
        - name: Generate RSA private key
          community.crypto.openssl_privatekey:
            path: "{{ plf_polaris_dir }}/rsa_key"
            size: 4096
            type: RSA
            format: "pkcs8"
            mode: "0600"
          tags:
            - rsa
            - setup

        - name: Generate RSA public key
          community.crypto.openssl_publickey:
            path: "{{ plf_polaris_dir }}/rsa_key.pub"
            privatekey_path: "{{ plf_polaris_dir }}/rsa_key"
            mode: "0644"
          tags:
            - rsa
            - setup

    - name: Verify RSA keys exist
      ansible.builtin.stat:
        path: "{{ item }}"
      loop: "{{ plf_key_files }}"
      register: key_stats
      tags:
        - rsa
        - verify

    - name: Fail if keys are missing
      ansible.builtin.fail:
        msg: "{{ item.item }} does not exist"
      when: not item.stat.exists
      loop: "{{ key_stats.results }}"
      loop_control:
        label: "{{ item.item }}"
      tags:
        - rsa
        - verify

    - name: Display key generation status
      ansible.builtin.debug:
        msg:
          - "RSA keys generated successfully"
          - "Private key location: {{ plf_polaris_dir }}/rsa_key"
          - "Public key location: {{ plf_polaris_dir }}/rsa_key.pub"
      tags:
        - rsa
        - verify

    - name: Check if postgresql.yaml exists (for password consistency)
      ansible.builtin.stat:
        path: "{{ plf_features_dir }}/postgresql.yaml"
      register: postgresql_yaml_stat
      tags:
        - bootstrap
        - k8s

    - name: Read existing postgresql password if file exists
      when: postgresql_yaml_stat.stat.exists
      block:
        - name: Read postgresql.yaml content
          ansible.builtin.slurp:
            src: "{{ plf_features_dir }}/postgresql.yaml"
          register: postgresql_yaml_content

        - name: Extract existing password from postgresql.yaml
          ansible.builtin.set_fact:
            existing_jdbc_password: >-
              {{ postgresql_yaml_content.content | b64decode | regex_search('postgresPassword:\s*(\S+)', '\1') | first | default('') }}
      tags:
        - bootstrap
        - k8s

    - name: Generate credentials
      ansible.builtin.set_fact:
        bootstrap_client_id:
          "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=8) }}"
        bootstrap_client_secret:
          "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=12) }}"
        plf_jdbc_password: >-
          {{ existing_jdbc_password | default('') | ternary(existing_jdbc_password, lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=12)) }}
      tags:
        - bootstrap
        - k8s

    - name: Check if config files exist
      ansible.builtin.stat:
        path: "{{ item.file }}"
      loop: "{{ plf_config_files }}"
      register: config_file_stats
      tags:
        - bootstrap
        - k8s

    - name: Create config files if they don't exist
      ansible.builtin.template:
        src: "{{ item.0.template }}"
        dest: "{{ item.0.file }}"
        mode: "0600"
      when: not item.1.stat.exists
      loop: "{{ plf_config_files | zip(config_file_stats.results) | list }}"
      loop_control:
        label: "{{ item.0.file }}"
      tags:
        - bootstrap
        - k8s

    - name: Ensure features directory exists
      ansible.builtin.file:
        path: "{{ plf_features_dir }}"
        state: directory
        mode: "0755"
      tags:
        - bootstrap
        - k8s
